### ISSUE TITLE
Taking more time to predicting

### ISSUE THREAD

**Issue by sandip-narwade** [alessiosavi/PyRecognizer#17]
PyRecognizer : Latest
Python version: 3.7
Operating System: Windows 7

While predicting it is taking almost 58 seconds. It too late response. I am not using GPU. 
Please find the below image.

![response time](https://user-images.githubusercontent.com/32532237/72042929-d7502c80-32d5-11ea-997d-95454c0f3454.JPG)

**Comment by alessiosavi** [comment]
Hi Sir, thank you for spent time on the issue.
Have you a GPU? The method for extract/encode the faces is `CNN`, so a GPU can be useful here.
The problems seems related to the `encoding_faces` phase. You can see that the most of the time is spent in line `Classifier.py:325`. You can reduce the `jitter` parameter in order to reduce the number of "transformation" made on the photo. An higher value on the `jitter` parameter is useful when deal with rotated photos. You can try two method in order to reduce the time:
 - Reduce the `jitter` parameter in order to don't deal with photo augmentation (`jitter`=300 means 300x time)
 - Replace the `CNN` with the `HOG` method.

Let me know if the time is reduced, i'm going to change the configuration file in order to deal with these 2 additional parameter.

**Comment by sandip-narwade** [comment]
Thank you Sir for instant updates.  I will check it

**Comment by alessiosavi** [comment]
With e45916d2a3eb8d8ffe2ae0cb6a709d217a64d2ed (v0.3.2), you can reach the max possible without touching the internal logic of the software. You can understand that the quality of the tool (only where the photos are quite tricky instead of be clean and with a recognizable face(s)) can be lower than the old one.

This because I've switched to `HOG` instead of use the `CNN` face detector, and because I've reduced the number of "augmentation" done on the photo.

**Comment by sandip-narwade** [comment]
good sound

**Comment by sandip-narwade** [comment]
The latest one working fine, Thank You...!

**Comment by alessiosavi** [comment]
Perfect, ill manage the custom tuning for the `jitter` and the `hog`/`cnn` in the future release
